translation spanish
ReentryGame/Languages pull request #10
Opened 2022-04-04 17:56 UTC by dewasha

translation to spanish

2022-04-04 17:56 UTC, dewasha commented
translation to spanish

2022-04-04 19:31 UTC, sundhaug92 requested changes
Some changes needed, some spurious/excessive escaped characters

2022-04-04 19:31 UTC, sundhaug92 commented on MainMenu/MainMenuUI/MainMenuUI.es-es.json
> +      "Text": "SFX\r\r\r\n\r\r\n\r\n"
Excessive `\r\n`

2022-04-04 19:31 UTC, sundhaug92 commented on MainMenu/MainMenuUI/MainMenuUI.es-es.json
> +      "Text": "Esto exportara\r\r\r datos del OBC, AGC y el panel LGC en tiempo real a los archivos dedicados in las carpetas de Exportación (en la carpeta AppData en Reentry). Esto puede usarse para
Excessive `\r\n`, possibly spurious `\r`

2022-04-04 19:31 UTC, sundhaug92 commented on MainMenu/MainMenuUI/MainMenuUI.es-es.json
> +      "Text": "Las sondas de reflejo son usadas para renderizar todo tipo de reflejos. Desde luces de reflejo de plantes mientras estás en la orbita (sondas generales), hasta los reflejos internos de
Excessive `\r\n`

2022-04-04 19:31 UTC, sundhaug92 commented on MainMenu/MainMenuUI/MainMenuUI.es-es.json
> +      "Text": "APAGADO: Todas las sondas de reflexión se apagarán\r\r\r\nBAJO: Las sondas críticas se actualizarán en catorce fotogramas, Resolución máxima: 256\r\r\r\nMEDIA: Las sondas críticas se a
Excessive `\r\n`, spurious `\ `

2022-04-04 19:31 UTC, sundhaug92 commented on MainMenu/MainMenuUI/MainMenuUI.es-es.json
> +      "Text": "Post Procesado\r\r\n\r\n"
Excessive `\r\n`

2022-04-05 08:54 UTC, sundhaug92 requested changes

2022-04-05 08:54 UTC, sundhaug92 commented on MainMenu/MainMenuUI/MainMenuUI.es-es.json
> +      "Text": "El Centro \rde Control de Misiones en Vivo, permite que multiples controladores apoyen una misión Apollo a traves del MOCR."
Spurious `\r`?

2022-04-05 08:54 UTC, sundhaug92 commented on MainMenu/MainMenuUI/MainMenuUI.es-es.json
> +      "Text": "Las sondas de reflejo son usadas para renderizar todo tipo de reflejos. Desde luces de reflejo de plantes mientras estás en la orbita (sondas generales), hasta los reflejos internos de
Spurious `\r` and `\n`

2022-04-05 08:54 UTC, sundhaug92 commented on MainMenu/MainMenuUI/MainMenuUI.es-es.json
> +      "Text": "Habilitar esto hará que los encuentros y las maniobras orbitales sean un poco más simples con algunas correcciones automáticas de guía cuando la lógica detecta errores acumulados o des
Invalid JSON? . appears outside of `""`

2022-04-05 08:54 UTC, sundhaug92 commented on MainMenu/MainMenuUI/MainMenuUI.es-es.json
> +      "Text": "Esto habilitará fallos o averias aleatorias en misiones que lo permitan (Free Play o misiones personalizadas). El sistema de fallos aleatorios lanzará un dado de probabilidades una vez
. appears after "

2022-04-05 08:54 UTC, sundhaug92 commented on MainMenu/MainMenuUI/MainMenuUI.es-es.json
> +      "Text": "Esto habilitará fallos o averias aleatorias en misiones que lo permitan (Free Play o misiones personalizadas). El sistema de fallos aleatorios lanzará un dado de probabilidades una vez
`"."` -> `."`

2022-04-05 09:06 UTC, merged